// <auto-generated />
namespace DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Quinta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quinta));
        
        string IMigrationMetadata.Id
        {
            get { return "202604080342197_Quinta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
